# experiment
seed_start: 2021
num_seeds: 10

num_data: 20
freq_report: 5
logdir: logs/

# environment
env_bandit: OfflineBandit # LinearBandit, LogLinearBandit, OfflineBandit
state_dim: 4
action_num: 16
reset_state_dist: uniform
feature_type: normal

# time-varying setting
tv:
  use: True
  type: faury
  v1_target: 0.11031
  v2_target: 0.018215
  bt: 1.57 # variation budget

# offline dataset
odata:
  use: True
  name_dataset: sigmoid_time100_train20_valid100
  num_steps: 100 # number of time steps
  train_per_step: 20 # number of training datapoints per step
  valid_per_step: 100 # number of validation datapoints per step
  size_batch: 100
  sample_prefs: True

# agent
algo: dpo
max_param_norm: 1. 
max_feature_norm: 4.
step_size: 0.1
num_iters: 1000
freq_eval: 5
reg_coef: 1.0
l2_coef: 0.01
is_adaptive: True
ada_coef: 0.1
delta: 0.1 # for performance guarantees

# sigmoidloss-particular
cs: 1.
ks: 1.
gamma: 0.7
gamma2: None

# action selection
action_selection: random
filter_actions: False
cov_init_coef: 1.
bonus_coef: 1.0
