name_or_path: NousResearch/Llama-2-7b-chat-hf
tokenizer_name_or_path: null
archive: null
block_name: LlamaDecoderLayer

policy_dtype: bfloat16
fsdp_policy_mp: null
reference_dtype: bfloat16

use_lora: True
lora_rank: 8
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - q-proj 
  - v_proj 
  - k_proj 
  - o_proj 
