# experiment
seed_start: 2021
num_seeds: 5

num_data: 20
freq_report: 5
logdir: logs/

wandb:
  use: false
  key: YOUR_KEY
  entity: YOUR_ENTITY
  project: project0
  group: group0

# environment
env_bandit: LinearBandit # LinearBandit, LogLinearBandit, OfflineBandit
state_dim: 1
action_num: 4
reset_state_dist: uniform
feature_type: normal

reward_v1: 0.018215
reward_v2: 0.11031

# time-varying setting
tv:
  use: False
  type: linear
  v1_target: 0.11031
  v2_target: 0.018215
  bt: 1.57 # variation budget

# offline dataset
odata:
  use: False
  name_dataset: sigmoid_time100_train20_valid100
  num_steps: 100 # number of time steps
  train_per_step: 20 # number of training datapoints per step
  valid_per_step: 100 # number of validation datapoints per step
  size_batch: 100
  drift_coef: 1.0 # if 1.0, the parameter becomes orthogonal to the original at the end of the drift
  sample_prefs: True

# agent
algo: dpo
max_param_norm: 1. 
max_feature_norm: 4.
step_size: 0.1
num_iters: 200
freq_eval: 20
reg_coef: 1.0
l2_coef: 0.01
is_adaptive: True
ada_coef: 0.1
delta: 0.1 # for performance guarantees

# sigmoidloss-particular
cs: 1.
ks: 1.
gamma: 1.
gamma2: None

# sliding-window dpo
use_sw: False
window_size: 50

# action selection
action_selection: random
filter_actions: False
cov_init_coef: 1.
bonus_coef: 1.0
