# do DPO preference-based training
name: ns_dpo

# the temperature parameter for DPO; lower values mean we care less about
#   the reference model
beta: ???
gamma: ???
normalise: true
sample: false

# Large T in the paper
current_time: ???