# do DPO preference-based training
name: sw_dpo

# the temperature parameter for DPO; lower values mean we care less about
#   the reference model
beta: ???

# Large T in the paper
current_time: ???

# window size
window_size: ???